Migrate to multistage Dockerfile
Demonsthere/rpg-cards pull request #5
Opened 2019-12-16 19:55 UTC by nipsufn

2019-12-16 20:10 UTC, Demonsthere requested changes

2019-12-16 20:10 UTC, Demonsthere commented on Dockerfile
> +RUN npm install mv graceful-fs fs-extra request path walk unzipper child_process ncp
Please use the `package.json` file to download dependencies instead

2019-12-16 21:24 UTC, Demonsthere commented
A few more suggestions:
- please don't delete the `custom-icons` and `class-icons` directories, as they are used by the `update-icons.js` script, and lack of them causes errors in the script:

```
Error [Error: ENOENT: no such file or directory, stat './resources/custom-icons'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: './resources/custom-icons'
}
```

2019-12-17 18:42 UTC, nipsufn commented
I've added back hastly removed directories and contents, improved the Dockerfile.

2019-12-17 20:54 UTC, Demonsthere approved these changes
LGTM :)

2019-12-17 21:58 UTC, merged